import { AllowedDepartments } from 'src/products/models/AllowedDepartments';
import { AllowedStockLevels } from 'src/products/models/AllowedStockLevels';
import { Product } from 'src/products/models/Product.model';

export const mockProductData: Product[] = [
  {
    name: 'Shirt',
    searchName: 'shirt',
    price: 700,
    description: 'a black t-shirt',
    dept: AllowedDepartments.CLOTHING,
    img_id: 'shirt_g0uouw.jpg',
    SKU: 1,
    stock: 999,
    stock_level: AllowedStockLevels.STOCKED,
  },
  {
    name: 'Jacket',
    searchName: 'jacket',
    price: 1700,
    description: 'light brown jacket',
    dept: AllowedDepartments.CLOTHING,
    img_id: 'jacket_rpl93p.jpg',
    SKU: 2,
    stock: 999,
    stock_level: AllowedStockLevels.STOCKED,
  },
  {
    name: 'Handbag',
    searchName: 'handbag',
    price: 2400,
    dept: AllowedDepartments.ACCESSORIES,
    description: 'black handbag made with full grain leather',
    img_id: 'handbag_hbxyrm.jpg',
    SKU: 3,
    stock: 999,
    stock_level: AllowedStockLevels.STOCKED,
  },
  {
    name: 'Backpack',
    searchName: 'backpack',
    price: 1800,
    dept: AllowedDepartments.ACCESSORIES,
    description: 'hand-stiched small black backpack.',
    img_id: 'backpack_zrzkuz.jpg',
    SKU: 4,
    stock: 999,
    stock_level: AllowedStockLevels.STOCKED,
  },
  {
    name: 'Tote',
    searchName: 'tote',
    price: 700,
    dept: AllowedDepartments.ACCESSORIES,
    description: 'a black tote bag',
    img_id: 'totebag_xn0oe3.jpg',
    SKU: 5,
    stock: 999,
    stock_level: AllowedStockLevels.STOCKED,
  },
  {
    name: 'Decorative Stick',
    searchName: 'decorative-stick',
    price: 700,
    dept: AllowedDepartments.INTERIOR,
    description: 'liven up your room with this stick',
    img_id: 'decorative-stick_ebeq95.jpg',
    SKU: 6,
    stock: 0,
    stock_level: AllowedStockLevels.OUT,
  },
  {
    name: 'Houseplant',
    searchName: 'houseplant',
    price: 800,
    dept: AllowedDepartments.INTERIOR,
    description: 'a plant',
    img_id: 'houseplant_qareey.jpg',
    SKU: 7,
    stock: 25,
    stock_level: AllowedStockLevels.LOW,
  },
  {
    name: 'Cassette Tape',
    searchName: 'cassette-tape',
    price: 7500,
    dept: AllowedDepartments.ACCESSORIES,
    description:
      '45-minute improvisational noise set by inHands founder, Elena Cojocaru. Limited to 25 Units. Signed and hand numbered.',
    img_id: 'cassette_umwz1w.jpg',
    SKU: 8,
    stock: 25,
    stock_level: AllowedStockLevels.LOW,
  },
];
