-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "orderTotal" DOUBLE PRECISION NOT NULL DEFAULT 0.0;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN     "price" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
